### ISSUE TITLE
Problem with navigation bar on iOS 15.

### ISSUE THREAD

**Issue by bobermiha** [michaelhenry/MHFacebookImageViewer#129]
Hello, I have a some bug with navigation bar when on iOS 15. I set background image for navBar appearance in AppDelegate, because of buggy UI of PHPickerViewController. And now it impact on ImageViewer.
![IMAGE 2022-06-02 12:08:14](https://user-images.githubusercontent.com/85123720/171573258-041e4f56-4aa7-4ec1-9911-b267fbb66337.jpg)
.

**Comment by michaelhenry** [comment]
how about applying the appearance only to that particular navbar rather than global?

**Comment by bobermiha** [comment]
> how about applying the appearance only to that particular navbar rather than global?

Unfortunately I can'n do it cause new PHPickerViewController is broken and if I wan to customise him - I have to set appearance global for whole app(That is what apple says - https://developer.apple.com/forums/thread/701712)
