### ISSUE TITLE
Image loading issue with remote url

### ISSUE THREAD

**Issue by Razanajam** [michaelhenry/MHFacebookImageViewer#130]
Its a nice library, if possible can you please test with the remote url, as your library is not caching the images, Everytime it takes time with white bg screen to load image from url, working perfectly fine with local images but issue with remote image, kinldy test on slow internet.

**Comment by rursache** [comment]
just use kingfisher and give ImageViewer the image from cache

**Comment by michaelhenry** [comment]
this should be fix on v3.8.8. please refer to this pr https://github.com/michaelhenry/ImageViewer.swift/pull/134
thanks
