### ISSUE TITLE
Image not centred Also the dark theme not working

### ISSUE THREAD

**Issue by ehsanmeet5** [michaelhenry/MHFacebookImageViewer#133]
Hi, i use the 3.3.7 version and I have an issue where the picture always shows on the right side and not in the centre of the screen.  It happened in OS 16.0.3 and iPhone 12 Pro Max.

the navigation content bar always stays white no way to change its color.
![IMG_E58F86066153-1](https://user-images.githubusercontent.com/111275870/196401597-3026aeb3-0ad9-4549-9566-2d29eb205065.jpeg)
<img width="736" alt="Screenshot 2022-10-18 at 12 08 16" src="https://user-images.githubusercontent.com/111275870/196401719-2ba0e047-ad12-4edf-bcd1-5d695ac77796.png">

**Comment by michaelhenry** [comment]
hi @ehsanmeet5 I have release a new version `3.3.8` please refer to this pr https://github.com/michaelhenry/ImageViewer.swift/pull/134

i wonder if this is related to this bug. Please let me know. thank you

**Comment by hirbod** [comment]
@michaelhenry I know this is an old issue, but it’s still happening for me with small images, like 400x400. It seems to occur about 90% of the time, while 10% of the time it works fine. It also appears to be more prone to this with PNG images.
