### ISSUE TITLE
Error: View is not in the window hierarchy.

### ISSUE THREAD

**Issue by jDomenech** [michaelhenry/MHFacebookImageViewer#135]
Hello and thanks for the library!
I'm using the latest versión (3.3.8), and sometimes I was getting this error:

`Attempt to present <ImageViewer_swift.ImageCarouselViewController: 0x10c047800> on <BaseNavigationViewController: 0x10c816400> (from <BaseNavigationViewController: 0x10c816400>) whose view is not in the window hierarchy.`

It was only happening on certain flows of the app, and the problem was here, the obtained rootVC using this method wasn't the presented one: 

`private var vc:UIViewController? {
        guard let rootVC = UIApplication.shared.keyWindow?.rootViewController
            else { return nil }
        return rootVC.presentedViewController != nil ? rootVC.presentedViewController : rootVC
    }`

After testing I ended up with a solution that fixes all the scenarios:

`private var vc:UIViewController? {
        guard var rootVC = UIApplication.shared.keyWindow?.rootViewController
            else { return nil }
        while let presentedVc = rootVC.presentedViewController {
            if let navVc = (presentedVc as? UINavigationController)?.viewControllers.last {
                rootVC = navVc
            } else if let tabVc = (presentedVc as? UITabBarController)?.selectedViewController {
                rootVC = tabVc
            } else {
                rootVC = presentedVc
            }
        }
        return rootVC
    }`

This way you can assure that you are at the presented view controller.

Thank you!

**Comment by michaelhenry** [comment]
hi @jDomenech im glad that you were able to resolve the problem. is there anything i could help you? thanks

cheers,

**Comment by jDomenech** [comment]
Hello, I shared this in case you want to fix in the next release.
Thank you!

**Comment by michaelhenry** [comment]
// TODO:
