### ISSUE TITLE
Image not centered and always show in the right side of the screen in iPad

### ISSUE THREAD

**Issue by KhusanM** [michaelhenry/MHFacebookImageViewer#137]
Hi, i use the 3.3.8 version and I have an issue where the picture always show in the right side and not in the center of the screen. Is there any way to solve this? It happened in OS 15.6.1 and iPad Air (5th generation).

![IMG_0132](https://user-images.githubusercontent.com/86423467/224295287-63b71094-917a-4bf0-aece-bb67493bb5e5.PNG)

**Comment by avillaindesire** [comment]
I started seeing this happen as well. Did you find a fix for it?

**Comment by avillaindesire** [comment]
@KhusanM I figured out a solution that works for me. In the ImageViewerController.swift file, there's an override func viewDidLoad() (line 84). I added 'self.imageView.layoutIfNeeded()' after line 95. (just after the DispatchQueue.main.async). I'm not sure if this solution will work for you, but I hope it puts you on the right track. Cheers.
