### ISSUE TITLE
Open block run twice

### ISSUE THREAD

**Issue by igrampe** [michaelhenry/MHFacebookImageViewer#29]
When I open photo viewer by clicking on photo the open block runs twice  because 
- (UITableViewCell*) tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath in MHFacebookImageViewer runs twice.
  So, how to fix it?

**Comment by ssqjd** [comment]
I have the same problems.

**Comment by ssqjd** [comment]
@igrampe do you fix it?
