### ISSUE TITLE
MHFacebookImageViewerCell: Sometimes __imageView has incorrect frame

### ISSUE THREAD

**Issue by petrovvy** [michaelhenry/MHFacebookImageViewer#37]
fix:
In method [MHFacebookImageViewerCell setImageURL: defaultImage: imageIndex:] it needs to add following code.
...
        if(_imageIndex==_initialIndex && !_isLoaded){
            __imageView.frame = _originalFrameRelativeToScreen;
            [UIView animateWithDuration:0.4f delay:0.0f options:0 animations:^{
                __imageView.frame = [self centerFrameFromImage:__imageView.image];
                CGAffineTransform transf = CGAffineTransformIdentity;
                // Root View Controller - move backward
                _rootViewController.view.transform = CGAffineTransformScale(transf, 0.95f, 0.95f);
                // Root View Controller - move forward
                //                _viewController.view.transform = CGAffineTransformScale(transf, 1.05f, 1.05f);
                _blackMask.alpha = 1;
            }   completion:^(BOOL finished) {
                if (finished) {
                    _isAnimating = NO;
                    _isLoaded = YES;
                    if(_openingBlock)
                        _openingBlock();
                }
            }];
-        } else {
-            __imageView.frame = [self centerFrameFromImage:__imageView.image];
      }
  ...

**Comment by michaelhenry** [comment]
please use the latest version. thank you
