### ISSUE TITLE
Orientation on iPad

### ISSUE THREAD

**Issue by lenhhoxung86** [michaelhenry/MHFacebookImageViewer#38]
Hello, thanks for your great component.
However, if I integrate on iPad, the landscape orientation is not supported. Can u support landscape orientation?

**Comment by kenpig** [comment]
I also encountered the same situation, how to deal with it?

**Comment by hlung** [comment]
see my answer in https://github.com/michaelhenry/MHFacebookImageViewer/issues/13

**Comment by michaelhenry** [comment]
please use the latest version. thank you
