### ISSUE TITLE
is this library dead?

### ISSUE THREAD

**Issue by jonasman** [michaelhenry/MHFacebookImageViewer#39]
There are no updates to it and too many bugs.

Anyone has an alternative to this lib?

**Comment by hlung** [comment]
I think it's dead :(

**Comment by gklka** [comment]
Do you know any alternative?

**Comment by michaelhenry** [comment]
please use the latest version. thank you

**Comment by michaelhenry** [comment]
Sorry i haven't maintain this for a long time :(
