### ISSUE TITLE
Incompatible with iOS8 UIAlertController

### ISSUE THREAD

**Issue by Hoya** [michaelhenry/MHFacebookImageViewer#40]
I've tweaked the controller a bit so that a custom button would try to present a UIAlertController (new in the iOS8 SDK) on top of the MHFacebookImageViewer. This doesn't work because it's "Attempting to present on a view controller whose view is not in the window hierarchy!". Tried a couple of stuff but failed, not sure how to work around this.

**Comment by royycc** [comment]
look at this:
http://stackoverflow.com/questions/26554894/how-to-present-uialertcontroller-when-not-in-a-view-controller
