### ISSUE TITLE
crash when swapping image 

### ISSUE THREAD

**Issue by fvisticot** [michaelhenry/MHFacebookImageViewer#43]
When I click on the image, the image is correctly zoomed and centered on the screen when if I try to move the image, a crash occurs

**Comment by ckakei** [comment]
This problem due to the super tableview is in different layer between iOS8 and iOS 7 

iOS 7 is in view.superview.superview.superview.superview.superview; 
but iOS8 is in view.superview.superview.superview.superview;

#pragma mark - Add Pan Gesture
- (void) addPanGestureToView:(UIView*)view
{
    _panGesture = [[UIPanGestureRecognizer alloc] initWithTarget:self action:@selector(gestureRecognizerDidPan:)];
    _panGesture.cancelsTouchesInView = NO;
    _panGesture.delegate = self;
  
    __weak UIView *weakSuperView = view.superview;   
    while (![weakSuperView isKindOfClass:[UITableView class]]) {
        weakSuperView = weakSuperView.superview;
        if (weakSuperView == Nil) {
            break;
        }
    }
    
    if ([weakSuperView isKindOfClass:[UITableView class]]) {
        [((UITableView*)weakSuperView).panGestureRecognizer requireGestureRecognizerToFail:_panGesture];
    }
    

    [view addGestureRecognizer:_panGesture];
    [_gestures addObject:_panGesture];

}

**Comment by allanscofield** [comment]
ckakei thanks for the resolution! :)

**Comment by kalmurzayev** [comment]
Had the same problem, this workaround helped a lot.

**Comment by tounaobun** [comment]
Great job.@ckakei

**Comment by derek-chim** [comment]
Good Job

**Comment by morugu** [comment]
worked it. GJ!

**Comment by nhanventuso** [comment]
thank you very much!
It work well.

**Comment by Neeraj204** [comment]
Is it for scrolling images left/right like gallery?

**Comment by michaelhenry** [comment]
please use the latest version. thank you
